title: Tine Jozelj
description: Internet Space Ship pilot and Full Stack web developer
author: Mentos1386

#Header
menu:
  Home: /
  Projects: /projects
  About: /about
  Github: https://github.com/mentos1386

more:
  Subscribe: http://eepurl.com/cDMV3L
  Twitter: https://twitter.com/Mentos1386
  Steam: http://steamcommunity.com/id/mentos1386

share:
  Twitter: Reading blog post :url by @mentos1386
  Reddit:
  Facebook:

# Github
github:
  history: true
  url: https://github.com/mentos1386/metalsmith-blog

# Miscellaneous
favicon: https://www.gravatar.com/avatar/170bf8b44ffd9f8ecd4fecae65ee8356s=128
gravatar: 170bf8b44ffd9f8ecd4fecae65ee8356
# Used for generating links (Twitter sharing)
domain: https://blog.tjo.space
